--INDIVIDUAL RESTORE SCRIPTS FOR A CLEAN BEGINNING OF EACH LAB.

--start lab3
--no backups as this lab uses independant, stand alone databases

------
SET PARSEONLY ON; 
GO
------

--start lab4 (=end of lab2)
USE [master]
ALTER DATABASE [DEV_Database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [DEV_Database] FROM  DISK = N'E:\QASQLDEV\Backups\lab04_1_start.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [DEV_Database] SET MULTI_USER

GO

--start lab5 (=end of lab4)
USE [master]
ALTER DATABASE [DEV_Database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [DEV_Database] FROM  DISK = N'E:\QASQLDEV\Backups\lab04END.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [DEV_Database] SET MULTI_USER

GO

--start lab6 (=end of lab5)
USE [master]
ALTER DATABASE [DEV_Database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [DEV_Database] FROM  DISK = N'E:\QASQLDEV\Backups\lab05END.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [DEV_Database] SET MULTI_USER

GO

--start lab7 (=end of lab6)
USE [master]
ALTER DATABASE [DEV_Database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [DEV_Database] FROM  DISK = N'E:\QASQLDEV\Backups\lab06END.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [DEV_Database] SET MULTI_USER

GO

--start lab8 (=end of lab7)
USE [master]
ALTER DATABASE [DEV_Database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [DEV_Database] FROM  DISK = N'E:\QASQLDEV\Backups\lab07END.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [DEV_Database] SET MULTI_USER

GO

--start lab9 (=end of lab8)
USE [master]
ALTER DATABASE [DEV_Database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [DEV_Database] FROM  DISK = N'E:\QASQLDEV\Backups\lab08END.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [DEV_Database] SET MULTI_USER

GO






